// Generated by gencpp from file rcj-soccer-sim/bot_measurements.msg
// DO NOT EDIT!


#ifndef RCJ-SOCCER-SIM_MESSAGE_BOT_MEASUREMENTS_H
#define RCJ-SOCCER-SIM_MESSAGE_BOT_MEASUREMENTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace rcj-soccer-sim
{
template <class ContainerAllocator>
struct bot_measurements_
{
  typedef bot_measurements_<ContainerAllocator> Type;

  bot_measurements_()
    : header()
    , pos_x(0.0)
    , pos_y(0.0)
    , theta(0.0)  {
    }
  bot_measurements_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pos_x(0.0)
    , pos_y(0.0)
    , theta(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _pos_x_type;
  _pos_x_type pos_x;

   typedef double _pos_y_type;
  _pos_y_type pos_y;

   typedef double _theta_type;
  _theta_type theta;





  typedef boost::shared_ptr< ::rcj-soccer-sim::bot_measurements_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rcj-soccer-sim::bot_measurements_<ContainerAllocator> const> ConstPtr;

}; // struct bot_measurements_

typedef ::rcj-soccer-sim::bot_measurements_<std::allocator<void> > bot_measurements;

typedef boost::shared_ptr< ::rcj-soccer-sim::bot_measurements > bot_measurementsPtr;
typedef boost::shared_ptr< ::rcj-soccer-sim::bot_measurements const> bot_measurementsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rcj-soccer-sim::bot_measurements_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rcj-soccer-sim::bot_measurements_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rcj-soccer-sim::bot_measurements_<ContainerAllocator1> & lhs, const ::rcj-soccer-sim::bot_measurements_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.pos_x == rhs.pos_x &&
    lhs.pos_y == rhs.pos_y &&
    lhs.theta == rhs.theta;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rcj-soccer-sim::bot_measurements_<ContainerAllocator1> & lhs, const ::rcj-soccer-sim::bot_measurements_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rcj-soccer-sim

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rcj-soccer-sim::bot_measurements_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rcj-soccer-sim::bot_measurements_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rcj-soccer-sim::bot_measurements_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rcj-soccer-sim::bot_measurements_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rcj-soccer-sim::bot_measurements_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rcj-soccer-sim::bot_measurements_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rcj-soccer-sim::bot_measurements_<ContainerAllocator> >
{
  static const char* value()
  {
    return "18e2daaa3e7df5052cfb9d58c0d3c7d0";
  }

  static const char* value(const ::rcj-soccer-sim::bot_measurements_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x18e2daaa3e7df505ULL;
  static const uint64_t static_value2 = 0x2cfb9d58c0d3c7d0ULL;
};

template<class ContainerAllocator>
struct DataType< ::rcj-soccer-sim::bot_measurements_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rcj-soccer-sim/bot_measurements";
  }

  static const char* value(const ::rcj-soccer-sim::bot_measurements_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rcj-soccer-sim::bot_measurements_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64 pos_x\n"
"float64 pos_y\n"
"float64 theta\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::rcj-soccer-sim::bot_measurements_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rcj-soccer-sim::bot_measurements_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pos_x);
      stream.next(m.pos_y);
      stream.next(m.theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct bot_measurements_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rcj-soccer-sim::bot_measurements_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rcj-soccer-sim::bot_measurements_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pos_x: ";
    Printer<double>::stream(s, indent + "  ", v.pos_x);
    s << indent << "pos_y: ";
    Printer<double>::stream(s, indent + "  ", v.pos_y);
    s << indent << "theta: ";
    Printer<double>::stream(s, indent + "  ", v.theta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RCJ-SOCCER-SIM_MESSAGE_BOT_MEASUREMENTS_H
