// Generated by gencpp from file rcj_soccer_sim/bot_command.msg
// DO NOT EDIT!


#ifndef RCJ_SOCCER_SIM_MESSAGE_BOT_COMMAND_H
#define RCJ_SOCCER_SIM_MESSAGE_BOT_COMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rcj_soccer_sim
{
template <class ContainerAllocator>
struct bot_command_
{
  typedef bot_command_<ContainerAllocator> Type;

  bot_command_()
    : left_wheel_speed(0.0)
    , right_wheel_speed(0.0)  {
    }
  bot_command_(const ContainerAllocator& _alloc)
    : left_wheel_speed(0.0)
    , right_wheel_speed(0.0)  {
  (void)_alloc;
    }



   typedef double _left_wheel_speed_type;
  _left_wheel_speed_type left_wheel_speed;

   typedef double _right_wheel_speed_type;
  _right_wheel_speed_type right_wheel_speed;





  typedef boost::shared_ptr< ::rcj_soccer_sim::bot_command_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rcj_soccer_sim::bot_command_<ContainerAllocator> const> ConstPtr;

}; // struct bot_command_

typedef ::rcj_soccer_sim::bot_command_<std::allocator<void> > bot_command;

typedef boost::shared_ptr< ::rcj_soccer_sim::bot_command > bot_commandPtr;
typedef boost::shared_ptr< ::rcj_soccer_sim::bot_command const> bot_commandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rcj_soccer_sim::bot_command_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rcj_soccer_sim::bot_command_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rcj_soccer_sim::bot_command_<ContainerAllocator1> & lhs, const ::rcj_soccer_sim::bot_command_<ContainerAllocator2> & rhs)
{
  return lhs.left_wheel_speed == rhs.left_wheel_speed &&
    lhs.right_wheel_speed == rhs.right_wheel_speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rcj_soccer_sim::bot_command_<ContainerAllocator1> & lhs, const ::rcj_soccer_sim::bot_command_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rcj_soccer_sim

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rcj_soccer_sim::bot_command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rcj_soccer_sim::bot_command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rcj_soccer_sim::bot_command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rcj_soccer_sim::bot_command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rcj_soccer_sim::bot_command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rcj_soccer_sim::bot_command_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rcj_soccer_sim::bot_command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2cb3b75b4d7e87ac43d11103b2af0a1e";
  }

  static const char* value(const ::rcj_soccer_sim::bot_command_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2cb3b75b4d7e87acULL;
  static const uint64_t static_value2 = 0x43d11103b2af0a1eULL;
};

template<class ContainerAllocator>
struct DataType< ::rcj_soccer_sim::bot_command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rcj_soccer_sim/bot_command";
  }

  static const char* value(const ::rcj_soccer_sim::bot_command_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rcj_soccer_sim::bot_command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 left_wheel_speed\n"
"float64 right_wheel_speed\n"
;
  }

  static const char* value(const ::rcj_soccer_sim::bot_command_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rcj_soccer_sim::bot_command_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left_wheel_speed);
      stream.next(m.right_wheel_speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct bot_command_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rcj_soccer_sim::bot_command_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rcj_soccer_sim::bot_command_<ContainerAllocator>& v)
  {
    s << indent << "left_wheel_speed: ";
    Printer<double>::stream(s, indent + "  ", v.left_wheel_speed);
    s << indent << "right_wheel_speed: ";
    Printer<double>::stream(s, indent + "  ", v.right_wheel_speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RCJ_SOCCER_SIM_MESSAGE_BOT_COMMAND_H
